import { beforeAll, describe, expect, it } from "bun:test";
import { initParser, parseModule } from "../../src/derive/ast.ts";
import { createClaimSet } from "../../src/derive/claims.ts";
import { deriveSpec } from "../../src/derive/index.ts";
import { functionName } from "../../src/derive/read.ts";
import {
  type FetchHelperFields,
  recognizeFetchHelper,
  recognizeRestFetchHelper,
  recognizeWriteHelper,
} from "../../src/derive/server/fetch-helper.ts";
import { generate } from "../../src/emit/index.ts";
import { formatAll, initFormatter } from "../../src/format.ts";
import { parseSpec } from "../../src/spec.ts";

beforeAll(async () => {
  await initParser();
  await initFormatter();
});

/** The emitted src/server.ts and nimbus.extension.json for a raw spec object. */
function emitted(raw: unknown): { server: string; manifest: string } {
  const files = formatAll(generate(parseSpec(raw)));
  const pick = (p: string): string => {
    const f = files.find((x) => x.path.join("/") === p);
    if (f === undefined) throw new Error(`no ${p} emitted`);
    return f.content;
  };
  return { server: pick("src/server.ts"), manifest: pick("nimbus.extension.json") };
}

// generated by this repository's emitter from fixtures/<name>.spec.json; not copied from Nimbus.

const NEWRELIC = [
  "async function nrGet(path: string): Promise<unknown> {",
  "  const res = await fetch(`https://api.newrelic.com${path}`, {",
  '    headers: { "X-Api-Key": apiKey(), Accept: "application/json" },',
  "  });",
  "  const text = await res.text();",
  "  if (!res.ok) {",
  "    throw new Error(`New Relic ${String(res.status)}: ${text.slice(0, 400)}`);",
  "  }",
  "  return JSON.parse(text) as unknown;",
  "}",
].join("\n");

const DATADOG = [
  "async function ddGet(path: string): Promise<unknown> {",
  "  const res = await fetch(`https://${siteHost()}${path}`, { headers: headers() });",
  "  const text = await res.text();",
  "  if (!res.ok) {",
  "    throw new Error(`Datadog ${String(res.status)}: ${text.slice(0, 400)}`);",
  "  }",
  "  return JSON.parse(text) as unknown;",
  "}",
].join("\n");

const GRAFANA = [
  "async function grafanaGet(path: string): Promise<unknown> {",
  '  const pathPart = path.startsWith("/") ? path : `/${path}`;',
  "  const res = await fetch(`${baseUrl()}${pathPart}`, {",
  "    headers: authHeaders(),",
  "  });",
  "  const text = await res.text();",
  "  if (!res.ok) {",
  "    throw new Error(`Grafana ${String(res.status)}: ${text.slice(0, 400)}`);",
  "  }",
  "  try {",
  "    return JSON.parse(text) as unknown;",
  "  } catch {",
  "    return { raw: text };",
  "  }",
  "}",
].join("\n");

const SENTRY = [
  "async function sentryGet(path: string): Promise<unknown> {",
  "  const res = await fetch(`${apiRoot()}${path}`, { headers: headers() });",
  "  const text = await res.text();",
  "  if (!res.ok) {",
  "    throw new Error(`Sentry ${String(res.status)}: ${text.slice(0, 400)}`);",
  "  }",
  "  return JSON.parse(text) as unknown;",
  "}",
].join("\n");

// Correlation defect test: two fetch() calls
const TWO_FETCHES = [
  "async function malformed(path: string): Promise<unknown> {",
  "  const dummy = await fetch(`https://example.com${path}`, {",
  '    headers: { "X-Dummy": "dummy" },',
  "  });",
  "  const res = await fetch(`https://api.example.com${path}`, {",
  '    headers: { "X-Api-Key": apiKey() },',
  "  });",
  "  const text = await res.text();",
  "  if (!res.ok) {",
  "    throw new Error(`Example ${String(res.status)}: ${text.slice(0, 400)}`);",
  "  }",
  "  return JSON.parse(text) as unknown;",
  "}",
].join("\n");

function run(source: string) {
  const statements = parseModule(source);
  const claims = createClaimSet();
  // `passthrough` is recovered beside the spec fields rather than among them (see
  // RecognizedFetchHelper) — unpacked here so every assertion below keeps comparing `fields`
  // against exactly the object the derived spec's `fetchHelper` is spread from.
  const matched = recognizeFetchHelper(statements, claims);
  return { fields: matched?.fields, passthrough: matched?.passthrough, claims, statements };
}

// Every helper recognizeFetchHelper must refuse, each with the reason it exists. One row per
// case: the assertions are identical in all of them — no fields recovered, and nothing claimed —
// so only the source and its rationale differ.
const REFUSED_HELPERS = [
  // Gap 1: rejects base template with accessor taking arguments
  [
    "rejects base template with accessor taking arguments",
    [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://${region(x)}${path}`, {",
      '    headers: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n"),
  ],

  // Gap 2, superseded by the final fix wave: a `pathPart` const whose init does not match the
  // normalizeLeadingSlash ternary used to be tolerated as inert clutter, because the body was
  // only probed for known shapes rather than walked positionally. Final fix wave (Fix 2):
  // recognizeFetchHelper now walks the body statement by statement, so an extra statement that
  // is not the exact sequence the emitter writes is rejected outright — the same class of bug
  // as the mutation tests below, just found first as a stale assumption in this pre-existing
  // test rather than as a fresh mutation.
  [
    "rejects a pathPart const whose init is not the normalizeLeadingSlash ternary, rather than tolerating it as clutter",
    [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const pathPart = somethingElse();",
      "  const res = await fetch(`https://api.example.com${path}`, {",
      '    headers: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n"),
  ],

  // Defect: a SpreadElement in the headers object has no `key`, and indexing into it
  // unguarded crashed the whole sweep on discord, google-meet, zzstandalone, zzwriterest,
  // zzwrite and zzwriteonly. Must reject the helper, not throw.
  [
    "rejects (without crashing) a headers object containing a spread",
    [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://api.example.com${path}`, {",
      '    headers: { ...common, "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n"),
  ],

  // I-2: a computed `headers` key (`{ [headers]: … }`) must not be read as though it declared a
  // property literally named "headers" just because the indexing variable happens to share that
  // name — the same KEY VARIABLE hazard `memberName`/`memberObject` guard on the member-expression
  // side. Reject rather than extract, the safe direction.
  [
    "rejects a computed [headers] key rather than treating it as the literal headers property",
    [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://api.example.com${path}`, {",
      '    [headers]: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n"),
  ],

  // Same hazard for hasUnexpectedFetchOption: a computed key elsewhere in the fetch options
  // object (not itself named "headers") is unresolvable, not simply "not headers, therefore
  // fine" — it must block the whole helper rather than be waved through.
  [
    "rejects a computed key elsewhere in the fetch options object, rather than ignoring it",
    [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://api.example.com${path}`, {",
      '    headers: { "X-Api-Key": apiKey() },',
      "    [opt]: controller.signal,",
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n"),
  ],

  // Gap 3: rejects inline header with accessor taking arguments
  [
    "rejects inline header with accessor taking arguments",
    [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://api.example.com${path}`, {",
      '    headers: { "X-Api-Key": apiKey(token), Accept: "application/json" },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n"),
  ],

  // --- Gap C near misses: jsonFallbackRaw is recovered from the read helper's final statement,
  // so that statement is classified rather than assumed. Each of these is one step off the
  // `try { return JSON.parse(text) as unknown; } catch { return { raw: text }; }` shape the
  // emitter writes, and must reject rather than be read as it. The positive side of Gap C — the
  // plain `return JSON.parse(text) as unknown;` ending — is asserted in its own test below.

  [
    "rejects a try/catch whose catch has a bound parameter, rather than treating it as the fallback shape",
    [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://api.example.com${path}`, {",
      '    headers: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  try {",
      "    return JSON.parse(text) as unknown;",
      "  } catch (err) {",
      "    return { raw: text };",
      "  }",
      "}",
    ].join("\n"),
  ],
  [
    "rejects a try/catch whose catch returns something other than { raw: text }",
    [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://api.example.com${path}`, {",
      '    headers: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  try {",
      "    return JSON.parse(text) as unknown;",
      "  } catch {",
      "    return null;",
      "  }",
      "}",
    ].join("\n"),
  ],
  [
    "rejects a try/catch with an extra statement in the try block",
    [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://api.example.com${path}`, {",
      '    headers: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  try {",
      "    const parsed = JSON.parse(text) as unknown;",
      "    return parsed;",
      "  } catch {",
      "    return { raw: text };",
      "  }",
      "}",
    ].join("\n"),
  ],
  [
    "rejects a final statement that is neither the plain return nor the fallback try/catch",
    [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://api.example.com${path}`, {",
      '    headers: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return text;",
      "}",
    ].join("\n"),
  ],

  // Over-claiming defect: reconstructBase dropped the quasi trailing the path expression
  // without checking it, so a template with text after `${path}` (`.json`) derived a base that
  // silently lost the suffix instead of being rejected. `${path}` here (with nothing after it)
  // is the one shape reconstructBase may accept; anything else after the expression must reject.
  [
    "rejects a fetch URL template with text after the path expression",
    [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://api.example.com${path}.json`, {",
      '    headers: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n"),
  ],

  // --- Computed-member sweep: same hazard as server/index.ts's isConnect. A computed member
  // (`x[name]`) has an Identifier `property` too — the KEY variable's name, not a property
  // name — so each of these must be rejected rather than read as the literal member access.

  [
    'rejects a computed path[startsWith]("/") instead of establishing path.startsWith',
    [
      "async function probeGet(path: string): Promise<unknown> {",
      '  const pathPart = path[startsWith]("/") ? path : `/${path}`;',
      "  const res = await fetch(`https://api.example.com${pathPart}`, {",
      '    headers: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n"),
  ],
  [
    "rejects a computed res[text]() instead of establishing res.text()",
    [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://api.example.com${path}`, {",
      '    headers: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res[text]();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n"),
  ],
  [
    "rejects a computed !res[ok] instead of establishing !res.ok",
    [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://api.example.com${path}`, {",
      '    headers: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res[ok]) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n"),
  ],
  [
    "rejects a computed JSON[parse](text) instead of establishing JSON.parse(text)",
    [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://api.example.com${path}`, {",
      '    headers: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON[parse](text) as unknown;",
      "}",
    ].join("\n"),
  ],

  // --- Hoisted base const: reconstructBase resolves a single non-final Identifier against a
  // module-scope `const X = "literal"`, because renderBaseConst can only ever hoist ONE const
  // holding the ENTIRE base (`const ${baseConst} = ${JSON.stringify(base)};`), and
  // FetchHelperSchema's own refine forbids mixing that const with a ${env.X} accessor. Anything
  // this shape cannot produce is refused rather than partially resolved — see reconstructBase's
  // own comment for why guessing at a partial base is worse than a visible blocker.

  [
    "refuses an identifier that does not resolve to a module-scope string const",
    [
      "const ZZ_API = someExpression();",
      "async function zzGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`${ZZ_API}${path}`, { headers: headers() });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`ZZ Hoist ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n"),
  ],
  [
    "refuses an identifier with no matching declaration at module scope at all",
    [
      "async function zzGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`${ZZ_API}${path}`, { headers: headers() });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`ZZ Hoist ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n"),
  ],
  [
    "refuses two hoisted consts in one base — renderBaseConst can only write one",
    [
      'const API_HOST = "https://api.example.com";',
      'const API_VERSION = "/v2";',
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`${API_HOST}${API_VERSION}${path}`, {",
      '    headers: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n"),
  ],
  [
    "refuses a hoisted const mixed with an env accessor — the schema refine forbids the combination",
    [
      'const BASE = "https://api.example.com";',
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`${BASE}${apiVersion()}${path}`, {",
      '    headers: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n"),
  ],
];

describe("recognizeFetchHelper", () => {
  it("recognizes newrelic (inline headers, static base)", () => {
    const { fields, claims, statements } = run(NEWRELIC);
    expect(fields).toEqual({
      local: "nrGet",
      base: "https://api.newrelic.com",
      serviceLabel: "New Relic",
      inlineHeaders: { "X-Api-Key": "${env.apiKey}", Accept: "application/json" },
    });
    expect(claims.unclaimed(statements)).toEqual([]);
  });

  it("recognizes datadog (accessor headers, env base)", () => {
    const { fields, claims, statements } = run(DATADOG);
    expect(fields).toEqual({
      local: "ddGet",
      base: "https://${env.siteHost}",
      serviceLabel: "Datadog",
      headers: "headers",
    });
    expect(claims.unclaimed(statements)).toEqual([]);
  });

  it("recognizes grafana (normalizeLeadingSlash, env base, jsonFallbackRaw)", () => {
    const { fields, claims, statements } = run(GRAFANA);
    expect(fields).toEqual({
      local: "grafanaGet",
      base: "${env.baseUrl}",
      serviceLabel: "Grafana",
      headers: "authHeaders",
      normalizeLeadingSlash: true,
      jsonFallbackRaw: true,
    });
    expect(claims.unclaimed(statements)).toEqual([]);
  });

  it("recognizes sentry (accessor headers, env base)", () => {
    const { fields, claims, statements } = run(SENTRY);
    expect(fields).toEqual({
      local: "sentryGet",
      base: "${env.apiRoot}",
      serviceLabel: "Sentry",
      headers: "headers",
    });
    expect(claims.unclaimed(statements)).toEqual([]);
  });

  // mercury/netlify/bitrise spell this "BASE"/"BASE"/"BITRISE_API"; discord/google-meet spell
  // it "DISCORD_API"/"MEET_BASE" (rest-kit's matchRestUrlConst below). The name is arbitrary —
  // reconstructBase resolves whatever identifier is there against the module's own consts.
  it("recognizes a hoisted base const (`${BASE}${path}`) and claims its module-scope const", () => {
    const source = [
      'const ZZ_API = "https://api.zzhoist.test";',
      "async function zzGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`${ZZ_API}${path}`, { headers: headers() });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`ZZ Hoist ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n");
    const { fields, claims, statements } = run(source);
    expect(fields).toEqual({
      local: "zzGet",
      base: "https://api.zzhoist.test",
      baseConst: "ZZ_API",
      serviceLabel: "ZZ Hoist",
      headers: "headers",
    });
    // The two trap this closes: the const declaration is claimed too (not just the function),
    // or the totality rule in deriveSpec would re-block the connector on the unclaimed
    // `const ZZ_API = "…";` statement it never asked recognizeFetchHelper about.
    expect(claims.unclaimed(statements)).toEqual([]);
  });

  it("accepts a hoisted base const and records fetchHelper.baseConst end to end through deriveSpec", () => {
    // The trap this task exists to avoid: recognizeFetchHelper alone returning fields proves
    // nothing if the hoisted const's own top-level statement is left unclaimed — the totality
    // rule would then re-block this exact connector on `statement:VariableDeclaration`.
    const raw = {
      name: "zzhoist",
      displayName: "ZZ Hoist",
      description: "Fixture for a hoisted base.",
      serviceLabel: "ZZ Hoist",
      style: "hand-rolled",
      env: [{ vars: ["ZZHOIST_TOKEN"], local: "headers", auth: "bearer", required: true }],
      fetchHelper: {
        local: "zzGet",
        base: "https://api.zzhoist.test",
        baseConst: "ZZ_API",
        headers: "headers",
      },
      tools: [
        {
          name: "zzhoist_item_list",
          description: "List items.",
          impl: "rest",
          path: "/v1/items",
          args: {},
        },
      ],
    };
    const d = deriveSpec(emitted(raw));
    expect(d.ok).toBe(true);
    if (d.ok) {
      const fh = d.spec["fetchHelper"] as Record<string, unknown>;
      expect(fh["baseConst"]).toBe("ZZ_API");
      expect(fh["base"]).toBe("https://api.zzhoist.test");
    }
  });

  it("rejects helpers with multiple fetch() calls", () => {
    const { fields, claims } = run(TWO_FETCHES);
    expect(fields).toBeUndefined();
    expect(claims.claims()).toEqual([]);
  });

  it("returns undefined for a function that is not a fetch helper", () => {
    expect(run("async function g(): Promise<void> {}").fields).toBeUndefined();
  });

  it("claims nothing when it does not recognize the helper", () => {
    const { claims } = run("async function g(): Promise<void> {}");
    expect(claims.claims()).toEqual([]);
  });

  // Every REFUSED_HELPERS row: no fields recovered, and nothing claimed. See that table for each
  // case's own rationale.
  it.each(REFUSED_HELPERS)("%s", (_name, src) => {
    const { fields, claims } = run(src);
    expect(fields).toBeUndefined();
    expect(claims.claims()).toEqual([]);
  });

  // Same hazard one level up from the headers-object spread in the table above: a spread in the
  // fetch options object itself, before `headers` is located within it. This must not crash
  // either — and here the spread genuinely does not bear on `headers`, so the helper is still
  // legitimately recognized; the recognizer records nothing about the spread it skipped, so this
  // is not an over-claim.
  it("does not crash on a fetch options object containing a spread", () => {
    const src = [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://api.example.com${path}`, {",
      "    ...commonOptions,",
      '    headers: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n");
    const { fields } = run(src);
    expect(fields).toEqual({
      local: "probeGet",
      base: "https://api.example.com",
      serviceLabel: "Probe",
      inlineHeaders: { "X-Api-Key": "${env.apiKey}" },
    });
  });

  // --- Gap C: jsonFallbackRaw, recovered from the read helper's final statement.

  it("omits jsonFallbackRaw for the plain `return JSON.parse(text) as unknown;` ending", () => {
    // NEWRELIC already exercises this path (see its own test above) — this one pins the
    // absence explicitly, independent of any other field.
    const { fields } = run(NEWRELIC);
    expect(fields?.jsonFallbackRaw).toBeUndefined();
  });

  // Final fix wave, Fix 2: claims.claim(s, "fetch-helper") claims the whole FunctionDeclaration
  // by byte range, so a mutation INSIDE the body used to be invisible to the totality rule —
  // containment already covered it. recognizeFetchHelper now walks the body positionally
  // instead of only `find()`-ing a fetch call and classifying the last statement, so each of
  // these mid-helper insertions is rejected as an unaccounted-for statement.
  describe("rejects a mutated body the totality rule alone would not catch", () => {
    it("an extra const inserted before the fetch call", () => {
      const src = [
        "async function probeGet(path: string): Promise<unknown> {",
        "  const retries = 3;",
        "  const res = await fetch(`https://api.example.com${path}`, {",
        '    headers: { "X-Api-Key": apiKey() },',
        "  });",
        "  const text = await res.text();",
        "  if (!res.ok) {",
        "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
        "  }",
        "  return JSON.parse(text) as unknown;",
        "}",
      ].join("\n");
      const { fields, claims } = run(src);
      expect(fields).toBeUndefined();
      expect(claims.claims()).toEqual([]);
    });

    it("a retry branch inserted between the fetch call and the !res.ok guard", () => {
      const src = [
        "async function probeGet(path: string): Promise<unknown> {",
        "  const res = await fetch(`https://api.example.com${path}`, {",
        '    headers: { "X-Api-Key": apiKey() },',
        "  });",
        "  const text = await res.text();",
        "  if (res.status === 429) {",
        "    await new Promise((r) => setTimeout(r, 1000));",
        "  }",
        "  if (!res.ok) {",
        "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
        "  }",
        "  return JSON.parse(text) as unknown;",
        "}",
      ].join("\n");
      const { fields, claims } = run(src);
      expect(fields).toBeUndefined();
      expect(claims.claims()).toEqual([]);
    });

    it("an extra property added to the fetch options object", () => {
      const src = [
        "async function probeGet(path: string): Promise<unknown> {",
        "  const res = await fetch(`https://api.example.com${path}`, {",
        '    headers: { "X-Api-Key": apiKey() },',
        "    signal: AbortSignal.timeout(5000),",
        "  });",
        "  const text = await res.text();",
        "  if (!res.ok) {",
        "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
        "  }",
        "  return JSON.parse(text) as unknown;",
        "}",
      ].join("\n");
      const { fields, claims } = run(src);
      expect(fields).toBeUndefined();
      expect(claims.claims()).toEqual([]);
    });
  });

  // --- The base template's own path interpolation, pinned to the variable this helper declares.
  // `reconstructBase` used to require only that the last expression be SOME identifier, which
  // recovers byte-identical fields from a helper interpolating something else and re-emits a URL
  // it never requested — the wrong-claim class. Both cases below reproduce with ZERO query tools,
  // on the byte-locked grafana and sentry shapes, so this laxity is not the passthrough's.

  it("refuses a base template interpolating `path` where the helper normalized it into `pathPart`", () => {
    // GRAFANA's own helper, with the fetch template reaching past its `pathPart` const to the raw
    // `path`. Every recovered field is unchanged, so nothing but this pin can reject it.
    const src = GRAFANA.replace("`${baseUrl()}${pathPart}`", "`${baseUrl()}${path}`");
    expect(src).not.toBe(GRAFANA);
    const { fields, claims } = run(src);
    expect(fields).toBeUndefined();
    expect(claims.claims()).toEqual([]);
  });

  it("refuses a base template interpolating a variable that is not the path at all", () => {
    const src = SENTRY.replace("`${apiRoot()}${path}`", "`${apiRoot()}${bogusVar}`");
    expect(src).not.toBe(SENTRY);
    expect(run(src).fields).toBeUndefined();
  });

  // --- The absolute-URL passthrough, emitted IFF the spec declares a query tool (hasQueryTool,
  // src/emit/server/fetch-helper.ts). Recovered as EVIDENCE about the tools, not as a
  // `fetchHelper` field: `deriveSharedStyleSpec` cross-checks it against the recognized tools,
  // and test/derive/query.test.ts drives both directions of that check end to end.

  describe("the query-tool passthrough const", () => {
    /** The zzquery-shaped read helper: no normalizeLeadingSlash, so the passthrough reads `path`. */
    const PASSTHROUGH = [
      "async function zzGet(path: string): Promise<unknown> {",
      '  const url = path.startsWith("http") ? path : `https://api.zzquery.test${path}`;',
      "  const res = await fetch(url, { headers: headers() });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`ZZ Query ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n");

    /**
     * The same helper with `normalizeLeadingSlash` as well — the only combination in which the
     * passthrough reads `pathPart` rather than `path`, and the only one in which the leading-slash
     * guard is widened. `renderFetchHelper` orders the two so the absolute-URL test runs BEFORE
     * the leading-slash rule; a URL forced through `` `/${path}` `` would emit "/https://…".
     */
    const NORMALIZED_PASSTHROUGH = [
      "async function zzGet(path: string): Promise<unknown> {",
      '  const pathPart = path.startsWith("http") || path.startsWith("/") ? path : `/${path}`;',
      '  const url = pathPart.startsWith("http") ? pathPart : `${baseUrl()}${pathPart}`;',
      "  const res = await fetch(url, {",
      "    headers: authHeaders(),",
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`ZZ Query ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n");

    it("recovers the base from the passthrough const, not from the fetch call's own argument", () => {
      // The fetch call now receives the bare identifier `url`, so a recognizer still reading its
      // first argument as the base template would refuse the helper outright.
      const { fields, passthrough, claims, statements } = run(PASSTHROUGH);
      expect(fields).toEqual({
        local: "zzGet",
        base: "https://api.zzquery.test",
        serviceLabel: "ZZ Query",
        headers: "headers",
      });
      expect(passthrough).toBe(true);
      expect(claims.unclaimed(statements)).toEqual([]);
    });

    it("reads the passthrough over `pathPart` when normalizeLeadingSlash also asked for that const", () => {
      const { fields, passthrough } = run(NORMALIZED_PASSTHROUGH);
      expect(fields).toEqual({
        local: "zzGet",
        base: "${env.baseUrl}",
        serviceLabel: "ZZ Query",
        headers: "authHeaders",
        normalizeLeadingSlash: true,
      });
      expect(passthrough).toBe(true);
    });

    it("reports passthrough: false for a helper with no query tool behind it", () => {
      // NEWRELIC is byte-locked and declares no query tool, so this is the negative half of the
      // cross-check's input, taken from a shape that cannot drift without failing diff:golden.
      expect(run(NEWRELIC).passthrough).toBe(false);
    });

    it("refuses the widened leading-slash guard without the passthrough const it comes with", () => {
      // Both are written from the same `hasQueryTool(spec)` call, so one alone is a shape
      // renderFetchHelper cannot produce — GRAFANA's own guard, widened and nothing else.
      const src = GRAFANA.replace(
        'path.startsWith("/") ? path',
        'path.startsWith("http") || path.startsWith("/") ? path',
      );
      expect(src).not.toBe(GRAFANA);
      const { fields, claims } = run(src);
      expect(fields).toBeUndefined();
      expect(claims.claims()).toEqual([]);
    });

    it("refuses the passthrough const beside an un-widened leading-slash guard", () => {
      // The mirror: the passthrough is present, but the guard ahead of it was never widened, so
      // an absolute URL would already have been mangled into "/https://…" one statement earlier.
      const src = NORMALIZED_PASSTHROUGH.replace(
        'path.startsWith("http") || path.startsWith("/") ? path',
        'path.startsWith("/") ? path',
      );
      expect(src).not.toBe(NORMALIZED_PASSTHROUGH);
      const { fields, claims } = run(src);
      expect(fields).toBeUndefined();
      expect(claims.claims()).toEqual([]);
    });

    it("refuses a passthrough const guarding `path` where the helper normalized it into `pathPart`", () => {
      // Both halves of the ternary are rewritten, so they still AGREE with each other — the fault
      // is that they name the wrong variable, one the leading-slash rule above has already
      // superseded. Caught by the httpArm/passthrough cross-check: the widened guard is still
      // there, but no passthrough const over `pathPart` is found beside it.
      const src = NORMALIZED_PASSTHROUGH.replace(
        'const url = pathPart.startsWith("http") ? pathPart',
        'const url = path.startsWith("http") ? path',
      );
      expect(src).not.toBe(NORMALIZED_PASSTHROUGH);
      expect(run(src).fields).toBeUndefined();
    });

    it("refuses a passthrough template interpolating a variable other than the one it guards", () => {
      // The wrong-claim hole this closes: the ternary's test and consequent agree on `pathPart`,
      // but the base template interpolates the UN-NORMALIZED `path`, so every field recovers
      // byte-identically and the derived spec re-emits a helper that fetches a different URL —
      // accepted, not rejected, until `passthroughUrlTemplate` pinned the template's own
      // interpolation too. Two checks now refuse it: that pin, and `reconstructBase`'s own, which
      // stopped accepting any identifier in the same fix round. Kept as a pair on purpose — this
      // test names the shape, and either side losing its pin should still fail something.
      const src = NORMALIZED_PASSTHROUGH.replace(
        "`${baseUrl()}${pathPart}`",
        "`${baseUrl()}${path}`",
      );
      expect(src).not.toBe(NORMALIZED_PASSTHROUGH);
      const { fields, claims } = run(src);
      expect(fields).toBeUndefined();
      expect(claims.claims()).toEqual([]);
    });

    it("refuses a passthrough template interpolating a variable that is not a path at all", () => {
      const src = NORMALIZED_PASSTHROUGH.replace(
        "`${baseUrl()}${pathPart}`",
        "`${baseUrl()}${bogusVar}`",
      );
      expect(src).not.toBe(NORMALIZED_PASSTHROUGH);
      expect(run(src).fields).toBeUndefined();
    });

    it("refuses a helper that declares the passthrough const and then fetches something else", () => {
      const src = PASSTHROUGH.replace("await fetch(url,", "await fetch(`https://elsewhere.test`,");
      expect(src).not.toBe(PASSTHROUGH);
      expect(run(src).fields).toBeUndefined();
    });
  });
});

// ---------------------------------------------------------------------------
// The write helper — renderWriteHelper. Emitted IFF some tool is non-GET, and carrying no spec
// field of its own: every line is derived from `fetchHelper`, `serviceLabel` and that fact. So it
// is claimed-and-verified whenever a read helper stands beside it, and is the module's ONLY
// source of those fields when one does not (a connector whose every tool is a write emits no read
// helper at all — see renderReadHelper).
// ---------------------------------------------------------------------------

/**
 * The two helpers a spec with one GET and one POST emits, hand-written here and PINNED against
 * real emitter output by the first test below — so a formatting or shape change in
 * renderWriteHelper fails loudly rather than leaving these constants quietly describing a shape
 * the emitter stopped writing.
 */
const ZZ_BOTH_READ = [
  "async function zzGet(path: string): Promise<unknown> {",
  "  const res = await fetch(`https://api.zzboth.test${path}`, { headers: headers() });",
  "  const text = await res.text();",
  "  if (!res.ok) {",
  "    throw new Error(`ZZ Both ${String(res.status)}: ${text.slice(0, 400)}`);",
  "  }",
  "  return JSON.parse(text) as unknown;",
  "}",
].join("\n");

const ZZ_BOTH_WRITE = [
  "async function zzGetSend(path: string, method: string, body: string | undefined): Promise<unknown> {",
  "  const res = await fetch(`https://api.zzboth.test${path}`, {",
  "    method,",
  '    headers: { ...headers(), "Content-Type": "application/json" },',
  "    ...(body === undefined ? {} : { body }),",
  "  });",
  "  const text = await res.text();",
  "  if (!res.ok) {",
  "    throw new Error(`ZZ Both ${String(res.status)}: ${text.slice(0, 400)}`);",
  "  }",
  "  try {",
  "    return JSON.parse(text) as unknown;",
  "  } catch {",
  "    return null;",
  "  }",
  "}",
].join("\n");

/** The fields `recognizeFetchHelper` recovers from ZZ_BOTH_READ — the write helper's cross-check. */
const ZZ_BOTH_FIELDS: FetchHelperFields = {
  local: "zzGet",
  base: "https://api.zzboth.test",
  serviceLabel: "ZZ Both",
  headers: "headers",
};

/** One GET and one POST, so renderReadHelper and renderWriteHelper both fire. */
const ZZ_BOTH_SPEC = {
  name: "zzboth",
  displayName: "ZZ Both",
  description: "Fixture for a module carrying both fetch helpers.",
  serviceLabel: "ZZ Both",
  style: "hand-rolled",
  env: [{ vars: ["ZZBOTH_TOKEN"], local: "headers", auth: "bearer" }],
  fetchHelper: { local: "zzGet", base: "https://api.zzboth.test", headers: "headers" },
  tools: [
    { name: "zzboth_item_list", description: "List items.", path: "/v1/items", args: {} },
    {
      name: "zzboth_item_create",
      description: "Create an item.",
      method: "POST",
      effect: "write",
      args: { title: { type: "string", min: 1 } },
      path: "/v1/items",
    },
  ],
};

function runWrite(source: string, readHelper?: FetchHelperFields) {
  const statements = parseModule(source);
  const claims = createClaimSet();
  const matched = recognizeWriteHelper(statements, claims, readHelper);
  return { fields: matched?.fields, passthrough: matched?.passthrough, claims, statements };
}

// Every write helper recognizeWriteHelper must refuse, each with the reason it exists. One row per
// case: the assertions are identical in all of them — no fields recovered, and nothing claimed.
// Each is one edit away from ZZ_BOTH_WRITE, which the first test pins to real emitter output, so
// a row that stops being a mutation of a producible shape fails there rather than here.
const REFUSED_WRITE_HELPERS: ReadonlyArray<readonly [string, string]> = [
  [
    "refuses `body: string` where the emitter writes `body: string | undefined`",
    ZZ_BOTH_WRITE.replace("body: string | undefined", "body: string"),
  ],
  [
    "refuses a third parameter that is not named `body`",
    ZZ_BOTH_WRITE.replace("body: string | undefined", "payload: string | undefined"),
  ],
  [
    "refuses a catch arm returning { raw: text } — that is the READ helper's jsonFallbackRaw form",
    ZZ_BOTH_WRITE.replace("    return null;", "    return { raw: text };"),
  ],
  [
    "refuses a missing `...(body === undefined ? {} : { body })` spread",
    ZZ_BOTH_WRITE.replace("    ...(body === undefined ? {} : { body }),\n", ""),
  ],
  [
    "refuses a body spread whose guard tests something other than `body === undefined`",
    ZZ_BOTH_WRITE.replace("body === undefined ?", "method === undefined ?"),
  ],
  [
    "refuses `{ body: body }` where the emitter writes the shorthand `{ body }`",
    ZZ_BOTH_WRITE.replace("{} : { body })", "{} : { body: body })"),
  ],
  [
    "refuses `method: method` where the emitter writes the shorthand `method,`",
    ZZ_BOTH_WRITE.replace("    method,", "    method: method,"),
  ],
  [
    "refuses a missing Content-Type header",
    ZZ_BOTH_WRITE.replace(
      '{ ...headers(), "Content-Type": "application/json" }',
      "{ ...headers() }",
    ),
  ],
  [
    "refuses an extra statement inserted mid-body, which the whole-function claim would otherwise cover",
    ZZ_BOTH_WRITE.replace(
      "  const text = await res.text();",
      "  const retries = 3;\n  const text = await res.text();",
    ),
  ],
  [
    "refuses a function whose name is exactly `Send` — fetchHelper.local is never empty",
    ZZ_BOTH_WRITE.replaceAll("zzGetSend", "Send"),
  ],
  [
    "refuses a function whose name does not end in Send at all",
    ZZ_BOTH_WRITE.replaceAll("zzGetSend", "zzGetPost"),
  ],
  // No row drops the `async` keyword: the body awaits `fetch` and `res.text()`, so a non-async
  // version of this function is not parseable JavaScript at all. `matchWriteHelperFunction`'s
  // `isAsyncFunction` guard therefore has no reachable near miss to pin — the same reason
  // `recognizeFetchHelper`'s own table has none.
  [
    "refuses a fetch URL template with text after the path expression",
    ZZ_BOTH_WRITE.replace("${path}`, {", "${path}.json`, {"),
  ],
];

describe("recognizeWriteHelper", () => {
  it("recognizes and claims the write helper `<local>Send`, which carries no spec field of its own — every line of renderWriteHelper is derived from fetchHelper, serviceLabel and the presence of a non-GET tool", () => {
    // Real emitter output, not a transcription: the two constants above are pinned against it
    // here so every refusal row below is provably one edit away from a shape renderWriteHelper
    // actually writes.
    const { server } = emitted(ZZ_BOTH_SPEC);
    expect(server).toContain(ZZ_BOTH_READ);
    expect(server).toContain(ZZ_BOTH_WRITE);

    const statements = parseModule(server);
    const claims = createClaimSet();
    const read = recognizeFetchHelper(statements, claims);
    expect(read?.fields).toEqual(ZZ_BOTH_FIELDS);

    const write = recognizeWriteHelper(statements, claims, read?.fields);
    // It recovers the same fields the read helper does — that is what makes it a cross-check
    // rather than a second source. `deriveSharedStyleSpec` spreads the READ helper's into the
    // spec; these are asserted only to show the two genuinely agree.
    expect(write?.fields).toEqual(ZZ_BOTH_FIELDS);
    expect(write?.passthrough).toBe(false);

    const fn = statements.find((s) => functionName(s) === "zzGetSend");
    expect(fn).toBeDefined();
    expect(claims.covers(fn!)).toBe(true);
  });

  it("recovers the fetch-helper fields on its own when the module has no read helper at all", () => {
    // zzwriteonly's shape: renderReadHelper emits nothing for a connector whose every tool is a
    // write, so `<local>Send` is the only place `local`, `base`, `serviceLabel` and the headers
    // appear. `local` comes off the function's own name, minus the `Send` suffix.
    const { fields, claims, statements } = runWrite(ZZ_BOTH_WRITE);
    expect(fields).toEqual(ZZ_BOTH_FIELDS);
    expect(claims.unclaimed(statements)).toEqual([]);
  });

  it("refuses a `<local>Send` whose error message names a different serviceLabel than the read helper's", () => {
    // Both helpers interpolate spec.serviceLabel, so a module where they disagree is one the
    // emitter cannot have written, and claiming it would derive a spec that regenerates neither.
    // On its own the mutated helper is perfectly well-formed — it recovers "ZZ Other" — which is
    // why only the cross-check can reject it.
    const src = ZZ_BOTH_WRITE.replace("`ZZ Both ${String", "`ZZ Other ${String");
    expect(src).not.toBe(ZZ_BOTH_WRITE);
    expect(runWrite(src).fields?.serviceLabel).toBe("ZZ Other");

    const { fields, claims } = runWrite(src, ZZ_BOTH_FIELDS);
    expect(fields).toBeUndefined();
    expect(claims.claims()).toEqual([]);
  });

  it("refuses a `<local>Send` whose base disagrees with the read helper's", () => {
    const src = ZZ_BOTH_WRITE.replace("https://api.zzboth.test", "https://elsewhere.test");
    expect(src).not.toBe(ZZ_BOTH_WRITE);
    const { fields, claims } = runWrite(src, ZZ_BOTH_FIELDS);
    expect(fields).toBeUndefined();
    expect(claims.claims()).toEqual([]);
  });

  it("refuses a `<local>Send` whose local does not match the read helper's", () => {
    // `${fh.local}Send` and the read helper's own name come from one spec field, so a module
    // where they disagree names a read helper the derived spec would not regenerate.
    const src = ZZ_BOTH_WRITE.replaceAll("zzGetSend", "otherGetSend");
    expect(src).not.toBe(ZZ_BOTH_WRITE);
    expect(runWrite(src).fields?.local).toBe("otherGet");
    expect(runWrite(src, ZZ_BOTH_FIELDS).fields).toBeUndefined();
  });

  it("refuses a `<local>Send` whose headers disagree with the read helper's", () => {
    const src = ZZ_BOTH_WRITE.replace("...headers()", "...otherHeaders()");
    expect(src).not.toBe(ZZ_BOTH_WRITE);
    expect(runWrite(src, ZZ_BOTH_FIELDS).fields).toBeUndefined();
  });

  it("reads inline headers out of the spread, matching what the read helper carries", () => {
    const src = ZZ_BOTH_WRITE.replace(
      "...headers()",
      '...{ "X-Api-Key": apiKey(), Accept: "application/json" }',
    );
    expect(src).not.toBe(ZZ_BOTH_WRITE);
    expect(runWrite(src).fields).toEqual({
      local: "zzGet",
      base: "https://api.zzboth.test",
      serviceLabel: "ZZ Both",
      inlineHeaders: { "X-Api-Key": "${env.apiKey}", Accept: "application/json" },
    });
  });

  it("refuses an awaited headers accessor, exactly as the read helper's own headersAccessor does", () => {
    // The client-credentials shape (`headerOption` awaits that accessor). recognizeEnv does not
    // model its token function either, so accepting it here would claim a helper in a module the
    // env recognizer then blocks anyway — zzwrite is that fixture.
    const src = ZZ_BOTH_WRITE.replace("...headers()", "...(await headers())");
    expect(src).not.toBe(ZZ_BOTH_WRITE);
    expect(runWrite(src).fields).toBeUndefined();
  });

  it("reads the absolute-URL passthrough const, which a query tool's presence puts in both helpers", () => {
    // renderWriteHelper writes the same statement renderFetchHelper does, under the same
    // hasQueryTool gate, and always over `path` — it has no pathPart form. Reused rather than
    // re-implemented: passthroughUrlTemplate already took pathVar as a parameter for this caller.
    const src = ZZ_BOTH_WRITE.replace(
      "  const res = await fetch(`https://api.zzboth.test${path}`, {",
      [
        '  const url = path.startsWith("http") ? path : `https://api.zzboth.test${path}`;',
        "  const res = await fetch(url, {",
      ].join("\n"),
    );
    expect(src).not.toBe(ZZ_BOTH_WRITE);
    const { fields, passthrough, claims, statements } = runWrite(src);
    expect(fields).toEqual(ZZ_BOTH_FIELDS);
    expect(passthrough).toBe(true);
    expect(claims.unclaimed(statements)).toEqual([]);
  });

  it("refuses a write helper that declares the passthrough const and then fetches something else", () => {
    const src = ZZ_BOTH_WRITE.replace(
      "  const res = await fetch(`https://api.zzboth.test${path}`, {",
      [
        '  const url = path.startsWith("http") ? path : `https://api.zzboth.test${path}`;',
        "  const res = await fetch(`https://elsewhere.test`, {",
      ].join("\n"),
    );
    expect(src).not.toBe(ZZ_BOTH_WRITE);
    expect(runWrite(src).fields).toBeUndefined();
  });

  it("recognizes a hoisted base const and claims its module-scope const", () => {
    const src = [
      'const ZZ_API = "https://api.zzboth.test";',
      ZZ_BOTH_WRITE.replace("`https://api.zzboth.test${path}`", "`${ZZ_API}${path}`"),
    ].join("\n");
    const { fields, claims, statements } = runWrite(src);
    expect(fields).toEqual({ ...ZZ_BOTH_FIELDS, baseConst: "ZZ_API" });
    // The same trap recognizeFetchHelper's hoisted-base test closes: without claiming the const's
    // own statement the totality rule re-blocks the connector on a statement:VariableDeclaration.
    expect(claims.unclaimed(statements)).toEqual([]);
  });

  it("returns undefined for a module with no `Send` function at all", () => {
    expect(runWrite(ZZ_BOTH_READ).fields).toBeUndefined();
  });

  // Every REFUSED_WRITE_HELPERS row: no fields recovered, and nothing claimed. See that table for
  // each case's own rationale. Each row asserts it actually mutated ZZ_BOTH_WRITE first — a
  // `replace` whose needle stopped matching would otherwise assert the pristine shape is refused,
  // which is the opposite of what the row claims.
  it.each(REFUSED_WRITE_HELPERS)("%s", (_name, src) => {
    expect(src).not.toBe(ZZ_BOTH_WRITE);
    const { fields, claims } = runWrite(src);
    expect(fields).toBeUndefined();
    expect(claims.claims()).toEqual([]);
  });
});

/**
 * Which HELPERS a module carries is decided entirely by its tools (`renderReadHelper` /
 * `renderWriteHelper`), so each one's presence is evidence to be held against the recognized
 * tools — the same class of cross-check `fetch-helper:query-passthrough-mismatch` already applies
 * one recognizer later. Neither recognizer can see the other's evidence, so `deriveSharedStyleSpec`
 * is where both are checked.
 *
 * Both modules below are otherwise perfectly recognizable: every helper matches, every tool
 * matches, and nothing is left unclaimed. Only the cross-check can reject them, which is why they
 * are built by ADDING a whole valid helper rather than by corrupting one.
 */
describe("the fetch helpers' presence is cross-checked against the tools' methods", () => {
  /** `source` with `helper` spliced in ahead of the wiring, where the emitter puts its helpers. */
  function withExtraHelper(source: string, helper: string): string {
    const anchor = "const mcp = new McpServer(";
    expect(source).toContain(anchor);
    return source.replace(anchor, `${helper}\n\n${anchor}`);
  }

  function blockerKinds(spec: unknown, helper: string): string[] {
    const { server, manifest } = emitted(spec);
    const derivation = deriveSpec({ server: withExtraHelper(server, helper), manifest });
    expect(derivation.ok).toBe(false);
    return derivation.ok ? [] : derivation.blockers.map((b) => b.kind);
  }

  it("refuses a read helper no tool would call — renderReadHelper emits none for a write-only spec", () => {
    const writeOnly = { ...ZZ_BOTH_SPEC, tools: [ZZ_BOTH_SPEC.tools[1]] };
    // Sanity: on its own this spec derives, and emits no read helper at all.
    expect(emitted(writeOnly).server).not.toContain("async function zzGet(");
    expect(deriveSpec(emitted(writeOnly)).ok).toBe(true);
    expect(blockerKinds(writeOnly, ZZ_BOTH_READ)).toEqual(["fetch-helper:read-helper-mismatch"]);
  });

  it("refuses a write helper no tool would call — renderWriteHelper emits none for an all-GET spec", () => {
    const readOnly = { ...ZZ_BOTH_SPEC, tools: [ZZ_BOTH_SPEC.tools[0]] };
    expect(emitted(readOnly).server).not.toContain("zzGetSend");
    expect(deriveSpec(emitted(readOnly)).ok).toBe(true);
    expect(blockerKinds(readOnly, ZZ_BOTH_WRITE)).toEqual(["fetch-helper:write-helper-mismatch"]);
  });
});

function runRest(source: string) {
  const statements = parseModule(source);
  const claims = createClaimSet();
  return { fields: recognizeRestFetchHelper(statements, claims), claims, statements };
}

// Generated by this repository's emitter from fixtures/zzstandalone.spec.json — confirmed by
// actually running the CLI's generate() pipeline, not copied from Nimbus (rest-kit's
// makeRestToolRegistrar fetch helper has no monorepo-only shared-module equivalent to copy from
// in the first place: renderRestKitFetchHelper writes it inline into every rest-kit server.ts).
const ZZ_FETCH = [
  "async function zzFetch(",
  "  token: string,",
  "  path: string,",
  "  init?: RequestInit,",
  "): Promise<{ ok: boolean; status: number; json: unknown; text: string }> {",
  '  const url = path.startsWith("http") ? path : `https://api.zzstandalone.test${path}`;',
  "  const res = await fetch(url, {",
  "    ...init,",
  "    headers: {",
  "      Authorization: `Bearer ${token}`,",
  "      ...(init?.headers as Record<string, string> | undefined),",
  "    },",
  "  });",
  "  const text = await res.text();",
  "  let json: unknown;",
  "  try {",
  "    json = JSON.parse(text) as unknown;",
  "  } catch {",
  "    json = null;",
  "  }",
  "  return { ok: res.ok, status: res.status, json, text };",
  "}",
].join("\n");

// Every source recognizeRestFetchHelper must refuse, each with the reason it exists. One row per
// case: the assertions are identical in all of them — no fields recovered, and nothing claimed —
// so only the source and its rationale differ.
const REFUSED_REST_HELPERS = [
  [
    "rejects a helper whose params are not exactly token, path, init",
    ZZ_FETCH.replace(
      "  token: string,\n  path: string,\n  init?: RequestInit,",
      "  path: string,\n  token: string,\n  init?: RequestInit,",
    ),
  ],

  // discord and google-meet write this form (fetchHelper.baseConst). matchRestUrlConst resolves
  // the identifier against a module-scope `const DISCORD_API = "…";` (see its own comment) — so
  // this case is refused only because that const is absent from this snippet, not because the
  // two-expression shape itself is unmodeled. The positive case, with the const declared, is
  // "recognizes a hoisted base const" below; discord/google-meet themselves still block, but on
  // their tools' query branch, a different recognizer's gap this task does not touch.
  [
    "refuses ${baseConst}${path} when the identifier resolves to nothing at module scope",
    ZZ_FETCH.replace("`https://api.zzstandalone.test${path}`", "`${DISCORD_API}${path}`"),
  ],
  [
    "refuses a url template with more than two expressions — a shape renderRestKitFetchHelper cannot write",
    [
      'const API_HOST = "https://api.example.com";',
      'const API_VERSION = "/v2";',
      ZZ_FETCH.replace(
        "`https://api.zzstandalone.test${path}`",
        "`${API_HOST}${API_VERSION}${path}`",
      ),
    ].join("\n"),
  ],

  [
    "rejects an extra statement inserted into the body",
    ZZ_FETCH.replace(
      "  const text = await res.text();",
      "  const extra = 1;\n  const text = await res.text();",
    ),
  ],
  [
    "rejects a try/catch that returns rather than assigns — the hand-style shape, not this one",
    ZZ_FETCH.replace(
      "  try {\n    json = JSON.parse(text) as unknown;\n  } catch {\n    json = null;\n  }",
      "  try {\n    return JSON.parse(text) as unknown;\n  } catch {\n    return { raw: text };\n  }",
    ),
  ],
  [
    "rejects a return statement missing a field",
    ZZ_FETCH.replace(
      "  return { ok: res.ok, status: res.status, json, text };",
      "  return { ok: res.ok, status: res.status, json };",
    ),
  ],
  [
    "rejects a `let json` that carries an initializer — the emitter always leaves it bare",
    ZZ_FETCH.replace("let json: unknown;", "let json: unknown = null;"),
  ],
  ["returns undefined for a module with no matching function at all", "const x = 1;"],
];

describe("recognizeRestFetchHelper", () => {
  it("recognizes zzFetch (literal base, no inline headers) — the real zzstandalone shape", () => {
    const { fields, claims, statements } = runRest(ZZ_FETCH);
    expect(fields).toEqual({ local: "zzFetch", base: "https://api.zzstandalone.test" });
    expect(claims.unclaimed(statements)).toEqual([]);
  });

  it("recognizes an inline extra header", () => {
    const source = ZZ_FETCH.replace(
      "      Authorization: `Bearer ${token}`,",
      '      Authorization: `Bearer ${token}`,\n      "X-Api-Version": "2",',
    );
    const { fields } = runRest(source);
    expect(fields).toEqual({
      local: "zzFetch",
      base: "https://api.zzstandalone.test",
      inlineHeaders: { "X-Api-Version": "2" },
    });
  });

  // Every REFUSED_REST_HELPERS row: no fields recovered, and nothing claimed. See that table for
  // each case's own rationale.
  it.each(REFUSED_REST_HELPERS)("%s", (_name, source) => {
    const { fields, claims } = runRest(source);
    expect(fields).toBeUndefined();
    expect(claims.claims()).toEqual([]);
  });

  // discord's own shape (fetchHelper.baseConst: "DISCORD_API"): the const is declared here,
  // unlike the REFUSED_REST_HELPERS row above, so matchRestUrlConst resolves it and claims the
  // const's own statement — the same trap `recognizeFetchHelper`'s hoisted-base test above
  // closes, mirrored for the rest-kit shape.
  it("recognizes a hoisted base const (`${baseConst}${path}`) and claims its module-scope const", () => {
    const source = [
      'const DISCORD_API = "https://discord.com/api/v10";',
      ZZ_FETCH.replace("`https://api.zzstandalone.test${path}`", "`${DISCORD_API}${path}`"),
    ].join("\n");
    const { fields, claims, statements } = runRest(source);
    expect(fields).toEqual({
      local: "zzFetch",
      base: "https://discord.com/api/v10",
      baseConst: "DISCORD_API",
    });
    expect(claims.unclaimed(statements)).toEqual([]);
  });
});
