/**
 * The published `ConnectorSpec` JSON Schema document, and the single function that produces it.
 *
 * Split out of scripts/build-schema.ts on this directory's standing convention — the pure part of
 * a harness lives in `_lib`, the driver stays a driver — but here the split carries a second load.
 * test/schema.test.ts byte-compares the checked-in document against a fresh build, and that
 * comparison is worth nothing if the test regenerates by a different route than the script writes
 * by. Both import `buildSchema` AND `SCHEMA_PATH` from here, so neither the bytes nor their
 * destination can diverge: a drift test that reconstructs the document its own way only proves the
 * two reconstructions agree.
 *
 * ## Why `{ io: "input" }`
 *
 * `z.toJSONSchema(ConnectorSpecSchema)` with no options THROWS — "Transforms cannot be represented
 * in JSON Schema", raised by `impl`'s `.transform(v => (v === "get" ? "rest" : v))`. Two options
 * make it succeed, and they describe different documents. `{ unrepresentable: "any" }` emits the
 * OUTPUT shape: what `parseSpec` returns, after every `.default()` has been filled in and every
 * transform applied. `{ io: "input" }` emits the shape a spec FILE has. An editor validates a file
 * a human is writing, so this is not merely the option that does not throw — it is the one whose
 * subject is the thing being validated.
 *
 * ## What this document cannot say, and why that is published rather than fixed
 *
 * `ConnectorSpecSchema` carries some forty `.refine`/`.superRefine` rules and NONE of them
 * survives the conversion — verified against the generated bytes: "must also declare", "only valid
 * on a tool" and "reserved" are all absent. So the published schema ACCEPTS specs the generator
 * REJECTS: an editor shows a file as clean and the CLI then refuses it.
 *
 * That is a false green in this repository's exact sense, and it cannot be closed — JSON Schema
 * has no way to say "this field is only valid when that one is set to this". So it is stated, in
 * three places that a reader can reach independently: SCHEMA_LIMITATION below lands in the
 * document's own `description`, README.md repeats it beside the instructions for wiring the schema
 * up, and test/schema.test.ts pins two concrete specs that fall through the gap.
 *
 * **Hand-encoding those rules here is the one thing not to do.** It would be a second source of
 * truth for the spec language — the thing this repo removes wherever it finds one — and it would
 * have gone stale within days of being written: `fetchHelper.base` and `serviceLabel` each grew a
 * new content rule while this file was being written, and both are of exactly the kind JSON Schema
 * cannot express.
 */

import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import { ConnectorSpecSchema } from "../../src/spec.ts";

/** Where the built document is checked in. Shared, so the writer and the drift test agree. */
export const SCHEMA_PATH = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "schema",
  "connector-spec.schema.json",
);

/**
 * The URL the checked-in document is served from, and therefore the URL an EDITOR-SIDE mapping
 * points at — README.md's `.vscode/settings.json` block quotes it, and test/schema.test.ts asserts
 * the two agree, so the instructions cannot come to point somewhere the `$id` does not.
 *
 * NOT the string a spec file names in its own `"$schema"` key. `ConnectorSpecSchema` is a
 * `z.strictObject`, so a spec carrying that key is refused — `Unrecognized key: "$schema"`, pinned
 * by "cannot be referenced from inside a spec file" in test/schema.test.ts. That route is the one
 * this change exists to warn against: it would make a file validate in the editor and fail at the
 * CLI, which is the inversion the published schema's stated limits are about.
 */
export const SCHEMA_ID =
  "https://raw.githubusercontent.com/nimbus-agent/create-nimbus-connector/main/schema/connector-spec.schema.json";

/**
 * The limitation, in the one wording all three places use.
 *
 * `validateSpec` is named alongside `parseSpec` because the two passes are genuinely separate and
 * the reserved-identifier rules live in the second one (src/validate.ts's RESERVED_IDENTIFIERS) —
 * attributing them to `parseSpec` would send a reader who went looking to the wrong file.
 */
export const SCHEMA_LIMITATION =
  "Refinements enforced by `parseSpec` and `validateSpec` (cross-field rules, reserved " +
  "identifiers, style-specific requirements) cannot be expressed in JSON Schema and are **not** " +
  "represented here. A spec that validates against this schema may still be rejected by the " +
  "generator.";

/**
 * The document, as the exact bytes that belong on disk — trailing newline included, so the
 * checked-in file is an ordinary text file and the comparison in test/schema.test.ts is a plain
 * string equality rather than a normalising one.
 *
 * `$schema` is destructured off and re-emitted first so the identifying keys read in the order a
 * human expects at the top of the file; everything after them is zod's output, untouched.
 */
export function buildSchema(): string {
  const { $schema, ...body } = z.toJSONSchema(ConnectorSpecSchema, { io: "input" });
  const doc = {
    $schema,
    $id: SCHEMA_ID,
    title: "ConnectorSpec",
    description:
      "The spec file create-nimbus-connector reads: the shape a human writes, before parseSpec " +
      `applies defaults and transforms. ${SCHEMA_LIMITATION}`,
    ...body,
  };
  return `${JSON.stringify(doc, undefined, 2)}\n`;
}
