import { describe, expect, it } from "bun:test";
import { parseModule } from "../../scripts/_lib/derive/ast.ts";
import { createClaimSet } from "../../scripts/_lib/derive/claims.ts";
import { recognizeFetchHelper } from "../../scripts/_lib/derive/server/fetch-helper.ts";

// generated by this repository's emitter from fixtures/<name>.spec.json; not copied from Nimbus.

const NEWRELIC = [
  "async function nrGet(path: string): Promise<unknown> {",
  "  const res = await fetch(`https://api.newrelic.com${path}`, {",
  '    headers: { "X-Api-Key": apiKey(), Accept: "application/json" },',
  "  });",
  "  const text = await res.text();",
  "  if (!res.ok) {",
  "    throw new Error(`New Relic ${String(res.status)}: ${text.slice(0, 400)}`);",
  "  }",
  "  return JSON.parse(text) as unknown;",
  "}",
].join("\n");

const DATADOG = [
  "async function ddGet(path: string): Promise<unknown> {",
  "  const res = await fetch(`https://${siteHost()}${path}`, { headers: headers() });",
  "  const text = await res.text();",
  "  if (!res.ok) {",
  "    throw new Error(`Datadog ${String(res.status)}: ${text.slice(0, 400)}`);",
  "  }",
  "  return JSON.parse(text) as unknown;",
  "}",
].join("\n");

const GRAFANA = [
  "async function grafanaGet(path: string): Promise<unknown> {",
  '  const pathPart = path.startsWith("/") ? path : `/${path}`;',
  "  const res = await fetch(`${baseUrl()}${pathPart}`, {",
  "    headers: authHeaders(),",
  "  });",
  "  const text = await res.text();",
  "  if (!res.ok) {",
  "    throw new Error(`Grafana ${String(res.status)}: ${text.slice(0, 400)}`);",
  "  }",
  "  try {",
  "    return JSON.parse(text) as unknown;",
  "  } catch {",
  "    return { raw: text };",
  "  }",
  "}",
].join("\n");

const SENTRY = [
  "async function sentryGet(path: string): Promise<unknown> {",
  "  const res = await fetch(`${apiRoot()}${path}`, { headers: headers() });",
  "  const text = await res.text();",
  "  if (!res.ok) {",
  "    throw new Error(`Sentry ${String(res.status)}: ${text.slice(0, 400)}`);",
  "  }",
  "  return JSON.parse(text) as unknown;",
  "}",
].join("\n");

// Correlation defect test: two fetch() calls
const TWO_FETCHES = [
  "async function malformed(path: string): Promise<unknown> {",
  "  const dummy = await fetch(`https://example.com${path}`, {",
  '    headers: { "X-Dummy": "dummy" },',
  "  });",
  "  const res = await fetch(`https://api.example.com${path}`, {",
  '    headers: { "X-Api-Key": apiKey() },',
  "  });",
  "  const text = await res.text();",
  "  if (!res.ok) {",
  "    throw new Error(`Example ${String(res.status)}: ${text.slice(0, 400)}`);",
  "  }",
  "  return JSON.parse(text) as unknown;",
  "}",
].join("\n");

function run(source: string) {
  const statements = parseModule(source);
  const claims = createClaimSet();
  return { fields: recognizeFetchHelper(statements, claims), claims, statements };
}

describe("recognizeFetchHelper", () => {
  it("recognizes newrelic (inline headers, static base)", () => {
    const { fields, claims, statements } = run(NEWRELIC);
    expect(fields).toEqual({
      local: "nrGet",
      base: "https://api.newrelic.com",
      serviceLabel: "New Relic",
      inlineHeaders: { "X-Api-Key": "${env.apiKey}", Accept: "application/json" },
    });
    expect(claims.unclaimed(statements)).toEqual([]);
  });

  it("recognizes datadog (accessor headers, env base)", () => {
    const { fields, claims, statements } = run(DATADOG);
    expect(fields).toEqual({
      local: "ddGet",
      base: "https://${env.siteHost}",
      serviceLabel: "Datadog",
      headers: "headers",
    });
    expect(claims.unclaimed(statements)).toEqual([]);
  });

  it("recognizes grafana (normalizeLeadingSlash, env base, jsonFallbackRaw)", () => {
    const { fields, claims, statements } = run(GRAFANA);
    expect(fields).toEqual({
      local: "grafanaGet",
      base: "${env.baseUrl}",
      serviceLabel: "Grafana",
      headers: "authHeaders",
      normalizeLeadingSlash: true,
      jsonFallbackRaw: true,
    });
    expect(claims.unclaimed(statements)).toEqual([]);
  });

  it("recognizes sentry (accessor headers, env base)", () => {
    const { fields, claims, statements } = run(SENTRY);
    expect(fields).toEqual({
      local: "sentryGet",
      base: "${env.apiRoot}",
      serviceLabel: "Sentry",
      headers: "headers",
    });
    expect(claims.unclaimed(statements)).toEqual([]);
  });

  it("rejects helpers with multiple fetch() calls", () => {
    const { fields, claims } = run(TWO_FETCHES);
    expect(fields).toBeUndefined();
    expect(claims.claims()).toEqual([]);
  });

  it("returns undefined for a function that is not a fetch helper", () => {
    expect(run("async function g(): Promise<void> {}").fields).toBeUndefined();
  });

  it("claims nothing when it does not recognize the helper", () => {
    const { claims } = run("async function g(): Promise<void> {}");
    expect(claims.claims()).toEqual([]);
  });

  // Gap 1: rejects base template with accessor taking arguments
  it("rejects base template with accessor taking arguments", () => {
    const src = [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://${region(x)}${path}`, {",
      '    headers: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n");
    const { fields, claims } = run(src);
    expect(fields).toBeUndefined();
    expect(claims.claims()).toEqual([]);
  });

  // Gap 2, superseded by the final fix wave: a `pathPart` const whose init does not match the
  // normalizeLeadingSlash ternary used to be tolerated as inert clutter, because the body was
  // only probed for known shapes rather than walked positionally. Final fix wave (Fix 2):
  // recognizeFetchHelper now walks the body statement by statement, so an extra statement that
  // is not the exact sequence the emitter writes is rejected outright — the same class of bug
  // as the mutation tests below, just found first as a stale assumption in this pre-existing
  // test rather than as a fresh mutation.
  it("rejects a pathPart const whose init is not the normalizeLeadingSlash ternary, rather than tolerating it as clutter", () => {
    const src = [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const pathPart = somethingElse();",
      "  const res = await fetch(`https://api.example.com${path}`, {",
      '    headers: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n");
    const { fields, claims } = run(src);
    expect(fields).toBeUndefined();
    expect(claims.claims()).toEqual([]);
  });

  // Defect: a SpreadElement in the headers object has no `key`, and indexing into it
  // unguarded crashed the whole sweep on discord, google-meet, zzstandalone, zzwriterest,
  // zzwrite and zzwriteonly. Must reject the helper, not throw.
  it("rejects (without crashing) a headers object containing a spread", () => {
    const src = [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://api.example.com${path}`, {",
      '    headers: { ...common, "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n");
    const { fields, claims } = run(src);
    expect(fields).toBeUndefined();
    expect(claims.claims()).toEqual([]);
  });

  // Same hazard one level up: a spread in the fetch options object itself, before `headers` is
  // located within it. This must not crash either — and here the spread genuinely does not
  // bear on `headers`, so the helper is still legitimately recognized; the recognizer records
  // nothing about the spread it skipped, so this is not an over-claim.
  it("does not crash on a fetch options object containing a spread", () => {
    const src = [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://api.example.com${path}`, {",
      "    ...commonOptions,",
      '    headers: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n");
    const { fields } = run(src);
    expect(fields).toEqual({
      local: "probeGet",
      base: "https://api.example.com",
      serviceLabel: "Probe",
      inlineHeaders: { "X-Api-Key": "${env.apiKey}" },
    });
  });

  // I-2: a computed `headers` key (`{ [headers]: … }`) must not be read as though it declared a
  // property literally named "headers" just because the indexing variable happens to share that
  // name — the same KEY VARIABLE hazard `memberName`/`memberObject` guard on the member-expression
  // side. Reject rather than extract, the safe direction.
  it("rejects a computed [headers] key rather than treating it as the literal headers property", () => {
    const src = [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://api.example.com${path}`, {",
      '    [headers]: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n");
    const { fields, claims } = run(src);
    expect(fields).toBeUndefined();
    expect(claims.claims()).toEqual([]);
  });

  // Same hazard for hasUnexpectedFetchOption: a computed key elsewhere in the fetch options
  // object (not itself named "headers") is unresolvable, not simply "not headers, therefore
  // fine" — it must block the whole helper rather than be waved through.
  it("rejects a computed key elsewhere in the fetch options object, rather than ignoring it", () => {
    const src = [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://api.example.com${path}`, {",
      '    headers: { "X-Api-Key": apiKey() },',
      "    [opt]: controller.signal,",
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n");
    const { fields, claims } = run(src);
    expect(fields).toBeUndefined();
    expect(claims.claims()).toEqual([]);
  });

  // Gap 3: rejects inline header with accessor taking arguments
  it("rejects inline header with accessor taking arguments", () => {
    const src = [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://api.example.com${path}`, {",
      '    headers: { "X-Api-Key": apiKey(token), Accept: "application/json" },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n");
    const { fields, claims } = run(src);
    expect(fields).toBeUndefined();
    expect(claims.claims()).toEqual([]);
  });

  // --- Gap C: jsonFallbackRaw, recovered from the read helper's final statement.

  it("omits jsonFallbackRaw for the plain `return JSON.parse(text) as unknown;` ending", () => {
    // NEWRELIC already exercises this path (see its own test above) — this one pins the
    // absence explicitly, independent of any other field.
    const { fields } = run(NEWRELIC);
    expect(fields?.jsonFallbackRaw).toBeUndefined();
  });

  it("rejects a try/catch whose catch has a bound parameter, rather than treating it as the fallback shape", () => {
    const src = [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://api.example.com${path}`, {",
      '    headers: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  try {",
      "    return JSON.parse(text) as unknown;",
      "  } catch (err) {",
      "    return { raw: text };",
      "  }",
      "}",
    ].join("\n");
    const { fields, claims } = run(src);
    expect(fields).toBeUndefined();
    expect(claims.claims()).toEqual([]);
  });

  it("rejects a try/catch whose catch returns something other than { raw: text }", () => {
    const src = [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://api.example.com${path}`, {",
      '    headers: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  try {",
      "    return JSON.parse(text) as unknown;",
      "  } catch {",
      "    return null;",
      "  }",
      "}",
    ].join("\n");
    const { fields, claims } = run(src);
    expect(fields).toBeUndefined();
    expect(claims.claims()).toEqual([]);
  });

  it("rejects a try/catch with an extra statement in the try block", () => {
    const src = [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://api.example.com${path}`, {",
      '    headers: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  try {",
      "    const parsed = JSON.parse(text) as unknown;",
      "    return parsed;",
      "  } catch {",
      "    return { raw: text };",
      "  }",
      "}",
    ].join("\n");
    const { fields, claims } = run(src);
    expect(fields).toBeUndefined();
    expect(claims.claims()).toEqual([]);
  });

  it("rejects a final statement that is neither the plain return nor the fallback try/catch", () => {
    const src = [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://api.example.com${path}`, {",
      '    headers: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return text;",
      "}",
    ].join("\n");
    const { fields, claims } = run(src);
    expect(fields).toBeUndefined();
    expect(claims.claims()).toEqual([]);
  });

  // Final fix wave, Fix 2: claims.claim(s, "fetch-helper") claims the whole FunctionDeclaration
  // by byte range, so a mutation INSIDE the body used to be invisible to the totality rule —
  // containment already covered it. recognizeFetchHelper now walks the body positionally
  // instead of only `find()`-ing a fetch call and classifying the last statement, so each of
  // these mid-helper insertions is rejected as an unaccounted-for statement.
  describe("rejects a mutated body the totality rule alone would not catch", () => {
    it("an extra const inserted before the fetch call", () => {
      const src = [
        "async function probeGet(path: string): Promise<unknown> {",
        "  const retries = 3;",
        "  const res = await fetch(`https://api.example.com${path}`, {",
        '    headers: { "X-Api-Key": apiKey() },',
        "  });",
        "  const text = await res.text();",
        "  if (!res.ok) {",
        "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
        "  }",
        "  return JSON.parse(text) as unknown;",
        "}",
      ].join("\n");
      const { fields, claims } = run(src);
      expect(fields).toBeUndefined();
      expect(claims.claims()).toEqual([]);
    });

    it("a retry branch inserted between the fetch call and the !res.ok guard", () => {
      const src = [
        "async function probeGet(path: string): Promise<unknown> {",
        "  const res = await fetch(`https://api.example.com${path}`, {",
        '    headers: { "X-Api-Key": apiKey() },',
        "  });",
        "  const text = await res.text();",
        "  if (res.status === 429) {",
        "    await new Promise((r) => setTimeout(r, 1000));",
        "  }",
        "  if (!res.ok) {",
        "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
        "  }",
        "  return JSON.parse(text) as unknown;",
        "}",
      ].join("\n");
      const { fields, claims } = run(src);
      expect(fields).toBeUndefined();
      expect(claims.claims()).toEqual([]);
    });

    it("an extra property added to the fetch options object", () => {
      const src = [
        "async function probeGet(path: string): Promise<unknown> {",
        "  const res = await fetch(`https://api.example.com${path}`, {",
        '    headers: { "X-Api-Key": apiKey() },',
        "    signal: AbortSignal.timeout(5000),",
        "  });",
        "  const text = await res.text();",
        "  if (!res.ok) {",
        "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
        "  }",
        "  return JSON.parse(text) as unknown;",
        "}",
      ].join("\n");
      const { fields, claims } = run(src);
      expect(fields).toBeUndefined();
      expect(claims.claims()).toEqual([]);
    });
  });

  // Over-claiming defect: reconstructBase dropped the quasi trailing the path expression
  // without checking it, so a template with text after `${path}` (`.json`) derived a base that
  // silently lost the suffix instead of being rejected. `${path}` here (with nothing after it)
  // is the one shape reconstructBase may accept; anything else after the expression must reject.
  it("rejects a fetch URL template with text after the path expression", () => {
    const src = [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://api.example.com${path}.json`, {",
      '    headers: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n");
    const { fields, claims } = run(src);
    expect(fields).toBeUndefined();
    expect(claims.claims()).toEqual([]);
  });

  // --- Computed-member sweep: same hazard as server/index.ts's isConnect. A computed member
  // (`x[name]`) has an Identifier `property` too — the KEY variable's name, not a property
  // name — so each of these must be rejected rather than read as the literal member access.

  it('rejects a computed path[startsWith]("/") instead of establishing path.startsWith', () => {
    const src = [
      "async function probeGet(path: string): Promise<unknown> {",
      '  const pathPart = path[startsWith]("/") ? path : `/${path}`;',
      "  const res = await fetch(`https://api.example.com${pathPart}`, {",
      '    headers: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n");
    const { fields, claims } = run(src);
    expect(fields).toBeUndefined();
    expect(claims.claims()).toEqual([]);
  });

  it("rejects a computed res[text]() instead of establishing res.text()", () => {
    const src = [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://api.example.com${path}`, {",
      '    headers: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res[text]();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n");
    const { fields, claims } = run(src);
    expect(fields).toBeUndefined();
    expect(claims.claims()).toEqual([]);
  });

  it("rejects a computed !res[ok] instead of establishing !res.ok", () => {
    const src = [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://api.example.com${path}`, {",
      '    headers: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res[ok]) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON.parse(text) as unknown;",
      "}",
    ].join("\n");
    const { fields, claims } = run(src);
    expect(fields).toBeUndefined();
    expect(claims.claims()).toEqual([]);
  });

  it("rejects a computed JSON[parse](text) instead of establishing JSON.parse(text)", () => {
    const src = [
      "async function probeGet(path: string): Promise<unknown> {",
      "  const res = await fetch(`https://api.example.com${path}`, {",
      '    headers: { "X-Api-Key": apiKey() },',
      "  });",
      "  const text = await res.text();",
      "  if (!res.ok) {",
      "    throw new Error(`Probe ${String(res.status)}: ${text.slice(0, 400)}`);",
      "  }",
      "  return JSON[parse](text) as unknown;",
      "}",
    ].join("\n");
    const { fields, claims } = run(src);
    expect(fields).toBeUndefined();
    expect(claims.claims()).toEqual([]);
  });
});
