import type { ConnectorSpec, ToolSpec } from "../spec.ts";
import type { GeneratedFile } from "../types.ts";

/**
 * PascalCase identifier fragment for `create<X>Syncable` / `map<X>ItemToItem`.
 * Same derivation as {@link import("../spec.ts").registrarName} — strip everything that
 * is not a JS identifier character from the title. For "Google Meet" this yields
 * "GoogleMeet", matching the real corpus's `createGoogleMeetSyncable`.
 */
function titleIdentifier(spec: ConnectorSpec): string {
  return spec.title.replaceAll(/[^A-Za-z0-9]/g, "");
}

/** snake_case service id — the corpus convention for a hyphenated package name. */
function serviceId(spec: ConnectorSpec): string {
  return spec.name.replaceAll("-", "_");
}

/**
 * The tool this scaffold drains. Corpus convention (not a schema field): a "list" tool's
 * name ends in "_list". The first one wins — a spec declaring more than one (e.g. two
 * resource types) gets only the first wired here; the rest need a hand-written syncable.
 */
function findListTool(spec: ConnectorSpec): ToolSpec {
  const found = spec.tools.find((t) => t.name.endsWith("_list"));
  if (found === undefined) {
    throw new Error(
      `emitWiring: no tool in "${spec.name}" has a name ending in "_list" — Gateway wiring ` +
        "drains one list tool via listConnectorItems(ctx, SERVICE_ID, LIST_TOOL_ID), and none " +
        "was found. Add a list tool, or wire this connector's sync by hand.",
    );
  }
  return found;
}

/** Other tools shaped like a list tool that this scaffold does NOT wire — surfaced so nothing is silently dropped. */
function otherListTools(spec: ConnectorSpec, chosen: ToolSpec): ToolSpec[] {
  return spec.tools.filter((t) => t.name.endsWith("_list") && t.name !== chosen.name);
}

function renderSync(spec: ConnectorSpec, listTool: ToolSpec): string {
  const id = titleIdentifier(spec);
  const svc = serviceId(spec);
  const mappingFn = `map${id}ItemToItem`;
  const defaultIntervalMs = spec.syncInterval * 1000;
  return `import { upsertIndexedItemForSync } from "../index/item-store.ts";
import type { Syncable, SyncContext, SyncResult } from "../sync/types.ts";
import { ${mappingFn} } from "./${spec.name}-mapping.ts";
import { listConnectorItems } from "./warehouse-sync-transport.ts";

const SERVICE_ID = ${JSON.stringify(svc)};
const LIST_TOOL_ID = ${JSON.stringify(listTool.name)};

/**
 * ${spec.serviceLabel} sync scaffold generated by create-nimbus-connector. Drains
 * {@link LIST_TOOL_ID} via {@link listConnectorItems} (spawns the connector once, drains
 * its paginated list) and upserts each item through {@link ${mappingFn}} — an unimplemented
 * stub; see ${spec.name}-mapping.ts. Adjust defaultIntervalMs / initialSyncDepthDays to taste.
 */
export function create${id}Syncable(): Syncable {
  return {
    serviceId: SERVICE_ID,
    defaultIntervalMs: ${defaultIntervalMs},
    initialSyncDepthDays: 30,
    async sync(ctx: SyncContext, cursor: string | null): Promise<SyncResult> {
      const t0 = performance.now();
      const raw = await listConnectorItems(ctx, SERVICE_ID, LIST_TOOL_ID);
      const now = Date.now();
      let upserted = 0;
      for (const rawItem of raw) {
        const mapped = ${mappingFn}(rawItem, { syncedAt: now });
        if (mapped !== null) {
          upsertIndexedItemForSync(ctx, mapped);
          upserted += 1;
        }
      }
      return {
        cursor,
        itemsUpserted: upserted,
        itemsDeleted: 0,
        hasMore: false,
        durationMs: Math.round(performance.now() - t0),
      };
    },
  };
}
`;
}

function renderMapping(spec: ConnectorSpec, listTool: ToolSpec): string {
  const id = titleIdentifier(spec);
  const mappingFn = `map${id}ItemToItem`;
  const message = JSON.stringify(
    `${mappingFn} is a create-nimbus-connector stub: no connector spec describes ` +
      `${spec.serviceLabel}'s API response shape, so the mapping cannot be generated. ` +
      `Implement the mapping from one raw "${listTool.name}" item to a local index item ` +
      "(the shape upsertIndexedItemForSync expects) before this connector can sync.",
  );
  return `/**
 * Stub. No connector spec contains ${spec.serviceLabel}'s API response shape, and a guessed
 * mapping that happens to compile is worse than one that plainly does not exist — see
 * create-nimbus-connector's Task 10 brief. Replace this body with the real mapping from one
 * raw "${listTool.name}" item to a local index item.
 */
export function ${mappingFn}(_raw: unknown, _ctx: { readonly syncedAt: number }): never {
  throw new Error(${message});
}
`;
}

/** Pure. Exactly two files: `<name>-sync.ts` and `<name>-mapping.ts` (the mapping throws). */
export function emitWiring(spec: ConnectorSpec): GeneratedFile[] {
  const listTool = findListTool(spec);
  return [
    { path: [`${spec.name}-sync.ts`], content: renderSync(spec, listTool) },
    { path: [`${spec.name}-mapping.ts`], content: renderMapping(spec, listTool) },
  ];
}

/**
 * The two pasteable edits, printed rather than written (see emitWiring's module doc / the
 * CLI --gateway-wiring help): a 93+-entry file in another repository, under another licence,
 * is not something this generator patches.
 *
 * The Task 10 brief named `connectors/gateway-syncable-ids.ts` as the second file. Reading
 * the real Nimbus source (packages/gateway/src/ipc/connector-rpc-shared.ts) shows that list
 * is checked only when a service id has NO connector-catalog entry, and is reserved for the
 * four local, filesystem-backed syncables (filesystem/blame/obsidian/openapi) — see that
 * file's own doc comment. An API-backed connector like the one this tool scaffolds already
 * gets a catalog entry, so `isGatewaySyncableServiceId` is never consulted for it, and adding
 * it to that list would be dead weight at best. The file that genuinely needs a new entry is
 * `connectors/connector-catalog.ts`: CONNECTOR_SERVICE_IDS (an id string) and
 * CONNECTOR_SYNC_INTERVAL_MS (a mapped type over every id in CONNECTOR_SERVICE_IDS — tsc
 * rejects the catalog file outright if the second is missing).
 */
export function renderWiringInstructions(spec: ConnectorSpec): string {
  const listTool = findListTool(spec);
  const id = titleIdentifier(spec);
  const svc = serviceId(spec);
  const others = otherListTools(spec, listTool);
  const otherNote =
    others.length === 0
      ? ""
      : `\nNote: ${others.map((t) => t.name).join(", ")} also look like list tools; only ` +
        `${listTool.name} was wired above. Wire the rest by hand if this connector needs them.\n`;

  return `Add to platform/assemble-sync-registrations.ts:
  import { create${id}Syncable } from "../connectors/${spec.name}-sync.ts";
  ...
  syncScheduler.register(create${id}Syncable());
${otherNote}
Add to connectors/connector-catalog.ts (NOT gateway-syncable-ids.ts — see this module's doc
comment for why that file, named in the original task brief, is the wrong target):
  CONNECTOR_SERVICE_IDS: add "${svc}"
  CONNECTOR_SYNC_INTERVAL_MS: add    ${svc}: ${spec.syncInterval * 1000},
(both are required together — CONNECTOR_SYNC_INTERVAL_MS is typed over every id in
CONNECTOR_SERVICE_IDS, so tsc rejects a mismatch.)`;
}
