import type { ConnectorSpec, ToolSpec } from "../spec.ts";
import type { GeneratedFile } from "../types.ts";

/**
 * PascalCase identifier fragment for `create<X>Syncable` / `map<X>ItemToItem`.
 * Same derivation as {@link import("../spec.ts").registrarName} — strip everything that
 * is not a JS identifier character from the title. For "Google Meet" this yields
 * "GoogleMeet", matching the real corpus's `createGoogleMeetSyncable`.
 */
function titleIdentifier(spec: ConnectorSpec): string {
  return spec.title.replaceAll(/[^A-Za-z0-9]/g, "");
}

/** snake_case service id — the corpus convention for a hyphenated package name. */
function serviceId(spec: ConnectorSpec): string {
  return spec.name.replaceAll("-", "_");
}

/**
 * The tool this scaffold drains. Corpus convention (not a schema field): a "list" tool's
 * name ends in "_list". The first one wins — a spec declaring more than one (e.g. two
 * resource types) gets only the first wired here; the rest need a hand-written syncable.
 */
function findListTool(spec: ConnectorSpec): ToolSpec {
  const found = spec.tools.find((t) => t.name.endsWith("_list"));
  if (found === undefined) {
    throw new Error(
      `emitWiring: no tool in "${spec.name}" has a name ending in "_list" — Gateway wiring ` +
        "drains one list tool, and none was found. Add a list tool, or wire this connector's " +
        "sync by hand.",
    );
  }
  return found;
}

/** Other tools shaped like a list tool that this scaffold does NOT wire — surfaced so nothing is silently dropped. */
function otherListTools(spec: ConnectorSpec, chosen: ToolSpec): ToolSpec[] {
  return spec.tools.filter((t) => t.name.endsWith("_list") && t.name !== chosen.name);
}

/**
 * Fix round 1, CRITICAL 1: this used to emit a WORKING body — a find/replace over
 * monte-carlo-sync.ts / bigeye-sync.ts's exact control flow (the `t0`/`raw`/`now`/`upserted`
 * loop draining `listConnectorItems`). The reviewer measured that assembly against the full
 * corpus: it exists in exactly 2 of ~98 connector files. Reproducing it — including
 * whitespace and comment placement — for every generated connector was a find/replace over
 * two specific AGPL files landing in an MIT repository, not "how the corpus does it".
 *
 * This now emits only what the Gateway's own `Syncable` type dictates (the shape, not
 * anyone's implementation choices) plus a TODO written in this project's own words. The body
 * throws rather than silently doing nothing, mirroring the mapping stub's precedent.
 */
function renderSync(spec: ConnectorSpec, listTool: ToolSpec): string {
  const id = titleIdentifier(spec);
  const svc = serviceId(spec);
  const mappingFn = `map${id}ItemToItem`;
  const defaultIntervalMs = spec.syncInterval * 1000;
  const message = JSON.stringify(
    `create${id}Syncable().sync is unimplemented — see the TODO comment in this function.`,
  );
  return `import type { Syncable, SyncContext, SyncResult } from "../sync/types.ts";

const SERVICE_ID = ${JSON.stringify(svc)};
const LIST_TOOL_ID = ${JSON.stringify(listTool.name)};

/**
 * ${spec.serviceLabel} sync SKELETON generated by create-nimbus-connector. This is not a
 * working implementation — sync() below throws. See ${spec.name}-mapping.ts (also a stub)
 * for the paired item mapping.
 */
export function create${id}Syncable(): Syncable {
  return {
    serviceId: SERVICE_ID,
    defaultIntervalMs: ${defaultIntervalMs},
    initialSyncDepthDays: 30,
    sync(_ctx: SyncContext, _cursor: string | null): Promise<SyncResult> {
      // TODO: implement this connector's sync. Roughly, in whatever shape this connector's
      // spawn/session mechanism requires (see an existing *-sync.ts in this directory for a
      // pattern matching this connector's kind — several exist, they are not interchangeable):
      //   1. Drain LIST_TOOL_ID (${JSON.stringify(listTool.name)}).
      //   2. Map each raw item to a local index item with ${mappingFn} (also unimplemented,
      //      in ${spec.name}-mapping.ts), skipping any item that does not map.
      //   3. Upsert every mapped item into the local index.
      //   4. Return a SyncResult: the new cursor, how many items were upserted/deleted,
      //      whether more pages remain, and how long the sync took.
      throw new Error(${message});
    },
  };
}
`;
}

function renderMapping(spec: ConnectorSpec, listTool: ToolSpec): string {
  const id = titleIdentifier(spec);
  const mappingFn = `map${id}ItemToItem`;
  const message = JSON.stringify(
    `${mappingFn} is a create-nimbus-connector stub: no connector spec describes ` +
      `${spec.serviceLabel}'s API response shape, so the mapping cannot be generated. ` +
      `Implement the mapping from one raw "${listTool.name}" item to a local index item ` +
      "(the shape upsertIndexedItemForSync expects) before this connector can sync.",
  );
  return `/**
 * Stub. No connector spec contains ${spec.serviceLabel}'s API response shape, and a guessed
 * mapping that happens to compile is worse than one that plainly does not exist — see
 * create-nimbus-connector's Task 10 brief. Replace this body with the real mapping from one
 * raw "${listTool.name}" item to a local index item.
 */
export function ${mappingFn}(_raw: unknown, _ctx: { readonly syncedAt: number }): never {
  throw new Error(${message});
}
`;
}

/** Pure. Exactly two files: `<name>-sync.ts` and `<name>-mapping.ts` (both throw when run). */
export function emitWiring(spec: ConnectorSpec): GeneratedFile[] {
  const listTool = findListTool(spec);
  return [
    { path: [`${spec.name}-sync.ts`], content: renderSync(spec, listTool) },
    { path: [`${spec.name}-mapping.ts`], content: renderMapping(spec, listTool) },
  ];
}

/**
 * The two pasteable edits, printed rather than written (see emitWiring's module doc / the
 * CLI --gateway-wiring help): a 93+-entry file in another repository, under another licence,
 * is not something this generator patches.
 *
 * The Task 10 brief named `connectors/gateway-syncable-ids.ts` as the second file. Reading
 * the real Nimbus source (packages/gateway/src/ipc/connector-rpc-shared.ts) shows that list
 * is checked only when a service id has NO connector-catalog entry, and is reserved for the
 * four local, filesystem-backed syncables (filesystem/blame/obsidian/openapi) — see that
 * file's own doc comment. An API-backed connector like the one this tool scaffolds already
 * gets a catalog entry, so `isGatewaySyncableServiceId` is never consulted for it, and adding
 * it to that list would be dead weight at best. The file that genuinely needs a new entry is
 * `connectors/connector-catalog.ts`: CONNECTOR_SERVICE_IDS (an id string) and
 * CONNECTOR_SYNC_INTERVAL_MS (a mapped type over every id in CONNECTOR_SERVICE_IDS — tsc
 * rejects the catalog file outright if the second is missing).
 *
 * Fix round 1, IMPORTANT: the registration call is NOT always zero-arg. In the real
 * assemble-sync-registrations.ts, `createMonteCarloSyncable()`/`createBigeyeSyncable()` take
 * no argument, but this project's own four golden fixtures — newrelic, datadog, grafana,
 * sentry — all register with an options object (`{ ensureXMcpRunning: () => ... }`). Printing
 * only the zero-arg form asserted the minority shape for the four connectors most likely to
 * be tried against this flag, so both are now shown and the user picks.
 */
export function renderWiringInstructions(spec: ConnectorSpec): string {
  const listTool = findListTool(spec);
  const id = titleIdentifier(spec);
  const svc = serviceId(spec);
  const others = otherListTools(spec, listTool);
  const otherNote =
    others.length === 0
      ? ""
      : `\nNote: ${others.map((t) => t.name).join(", ")} also look like list tools; only ` +
        `${listTool.name} was wired above. Wire the rest by hand if this connector needs them.\n`;

  return `Add to platform/assemble-sync-registrations.ts:
  import { create${id}Syncable } from "../connectors/${spec.name}-sync.ts";
  ...
  syncScheduler.register(create${id}Syncable());
    -- OR, if this connector needs an injected dependency (most do — e.g. an
    -- "ensure<X>McpRunning" callback tied to how it is spawned; see the newrelic/datadog/
    -- grafana/sentry entries in that file for the shape most connectors use):
  syncScheduler.register(
    create${id}Syncable({
      /* whatever this connector's Syncable options require */
    }),
  );
${otherNote}
Add to connectors/connector-catalog.ts (NOT gateway-syncable-ids.ts — see this module's doc
comment for why that file, named in the original task brief, is the wrong target):
  CONNECTOR_SERVICE_IDS: add "${svc}"
  CONNECTOR_SYNC_INTERVAL_MS: add    ${svc}: ${spec.syncInterval * 1000},
(both are required together — CONNECTOR_SYNC_INTERVAL_MS is typed over every id in
CONNECTOR_SERVICE_IDS, so tsc rejects a mismatch.)`;
}
